import "cypress-wait-until"
import 'cypress-file-upload'
describe('Etvas Test', () => {
    it('Campaign', () =>{
        cy.visit('https://partners.helloetvas-dev.xyz/')
        cy.get('input[name="email"]').first().type('rares.niculai+test@etvas.com')
        cy.get('button').click()
        cy.get('input[name="password"]').first().type('Secret12345')
        cy.get("button[type='submit']").first().click()

        cy.waitUntil(() => cy.url().should('eq','https://partners.helloetvas-dev.xyz/'))

        cy.get('[href="/campaigns"]').click()
        cy.contains('button', 'Cashbacks').should('not.be.disabled').click()
        

        cy.get('[data-testid="campaigns-list-status"]').first()
        .should('have.text', 'Restricted')

        cy.get('[data-testid="campaigns-list-status"]')
        cy.contains('draft campaign')
        .parent()
        .parent()
        .parent()
        .parent()
        .find('> [data-testid="campaigns-list-status"]').first()
        .should('have.text', 'Draft')

        cy.get('[data-testid="campaigns-list-status"]')
        cy.contains('not started campaign')
        .parent()
        .parent()
        .parent()
        .parent()
        .find('> [data-testid="campaigns-list-status"]')
        .should('have.text', 'Not Started')

        cy.get('[data-testid="campaigns-list-status"]')
        cy.contains('pending campaign')
        .parent()
        .parent()
        .parent()
        .parent()
        .find('> [data-testid="campaigns-list-status"]')
        .should('have.text', 'Pending')

        cy.get('[data-testid="campaigns-list-status"]')
        cy.contains('suspended campaign')
        .parent()
        .parent()
        .parent()
        .parent()
        .find('> [data-testid="campaigns-list-status"]')
        .should('have.text', 'Suspended')

        cy.get('[data-testid="campaigns-list-status"]')
        cy.contains('running campaign')
        .parent()
        .parent()
        .parent()
        .parent()
        .find('> [data-testid="campaigns-list-status"]')
        .should('have.text', 'Running')

        cy.get('[data-testid="campaigns-list-status"]')
        cy.contains('rejected offer')
        .parent()
        .parent()
        .parent()
        .parent()
        .find('> [data-testid="campaigns-list-status"]')
        .should('have.text', 'Rejected')

        cy.get('[data-testid="campaigns-list-status"]')
        cy.contains('stopped campaign')
        .parent()
        .parent()
        .parent()
        .parent()
        .find('> [data-testid="campaigns-list-status"]')
        .should('have.text', 'Stopped')

        cy.get('[data-testid="campaigns-list-status"]')
        cy.contains('expired campaign')
        .parent()
        .parent()
        .parent()
        .parent()
        .find('> [data-testid="campaigns-list-status"]')
        .should('have.text', 'Expired')
    })
})